Parse 'expires_in' implicit flow response parameter
danilobuerger/redux-implicit-oauth2 pull request #5
Opened 2017-05-17 15:51 UTC by duergner

This will allow parsing the OAuth2.0 Spec `expires_in` redirect response parameter and add it both to the local storage as well as expose it on the state.

It will actually not persist `expires_in` directly but rather persist the derived `expires_at` value as this will directly allow using it even after being read from local storage.

If the token is already expired when trying to read it from local storage it is not used but set to null instead.

2017-05-17 15:52 UTC, duergner commented
@danilobuerger again a small PR to add some desired functionality to your library. Let me know in case you would prefer some changes and I'd be happy to incorporate them.

2017-05-17 20:57 UTC, danilobuerger requested changes
@duergner Thanks for the PR! Just some minor feedback.

2017-05-17 20:57 UTC, danilobuerger commented on src/actions.js
> +const loginSuccess = (token, expires_at) => ({
Please replace `expires_at` with `expiresAt` everywhere.

2017-05-17 20:57 UTC, danilobuerger commented on src/oauth2.js
> +        expires_at: response.expires_in ? new Date().getTime() + parseInt(response.expires_in) * 1000 : null
What happens if `parseInt` returns `NaN`?

2017-05-18 06:21 UTC, duergner commented on src/oauth2.js
> +        expires_at: response.expires_in ? new Date().getTime() + parseInt(response.expires_in) * 1000 : null
This would violate the OAuth2 spec. But I added a `isNaN` check just to make sure.

2017-05-18 06:21 UTC, duergner commented
@danilobuerger addressed the review comments

2017-05-18 14:18 UTC, danilobuerger commented on src/oauth2.js
> +        expiresAt: response.expires_in && !isNaN(response.expires_in) ? new Date().getTime() + parseInt(response.expires_in) * 1000 : null
Yeah, I just want to be defensive about what the auth server returns. However now I see another Problem:
```
isNaN("") === false
isNaN(parseInt("")) === true
```
We should probably do `parseInt` first, and then `isNaN`. Maybe something like (pseudo code off the top of my head):

```
const expiresIn = response.expires_in ? parseInt(response.expires_in) : NaN
const result = {
  token: response.access_token,
  expiresAt: isNaN(expiresIn) ? null : new Date().getTime() + expiresIn * 1000
}
```

2017-05-18 14:31 UTC, duergner commented
@danilobuerger changed it accordingly

2017-05-18 14:33 UTC, danilobuerger approved these changes

2017-05-18 14:41 UTC, danilobuerger commented
@duergner Thanks again for the great work, I really appreciate it. Would you mind squashing & amending (if I do it, we would loose your info & signature)? Afterward, I would merge it and cut a new release.

2017-05-18 15:26 UTC, duergner commented
Go ahead

2017-05-18 15:30 UTC, merged

2017-05-18 15:37 UTC, danilobuerger commented
released